{
 "title": "Postgresql cluster walg/pghoard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Time since last basebackup upload",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "walg_last_upload{type=\"xlog\"} * 1000"
    }
   ]
  },
  {
   "title": "Time since last incremental upload",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "walg_last_upload{type=\"basebackup\"} * 1000"
    }
   ]
  },
  {
   "title": "Wal count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "walg_total_remote_wal_count" }
   ]
  },
  {
   "title": "Oldest valid basebackup",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "walg_oldest_valid_basebackup * 1000",
     "legendFormat": "{{where}}"
    }
   ]
  },
  {
   "title": "PGHoard Exception",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "walg_exception", "legendFormat": "{{where}}" }
   ]
  },
  {
   "title": "Valid basebackup count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "walg_basebackup_count", "legendFormat": "{{where}}" }
   ]
  },
  {
   "title": "xlog since basebackup",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "walg_xlogs_since_basebackup" }
   ]
  },
  {
   "title": "Missing xlog at end",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "walg_missing_remote_wal_segment_at_end",
     "legendFormat": "{{where}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[2m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Wal segment count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "walg_total_remote_wal_count", "legendFormat": "Uploaded" },
    {
     "expr": "walg_missing_remote_wal_segment",
     "legendFormat": "Missing"
    }
   ]
  },
  {
   "title": "Valid basebackup count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "walg_valid_basebackup_count", "legendFormat": "Valid basebackup count" }
   ]
  },
  {
   "title": "Oldest valid base backup age",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - walg_oldest_valid_basebackup",
     "legendFormat": "Oldest valid base backup age"
    }
   ]
  },
  {
   "title": "PGHoard Exception",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "walg_exception", "legendFormat": "{{where}}: {{exception}}" }
   ]
  },
  {
   "title": "basebackups",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    { "expr": "walg_basebackup * 1000", "legendFormat": "{{start_wal_segment}}" }
   ]
  }
 ]
}